language: node_js
node_js:
  - "8"

cache: npm

install: npm install

before_deploy: 
  - npm run build

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_KEY"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false
