language: node_js
node_js:
  - "8"

cache: npm

install: npm install


script: npm run build
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$API_TOKEN"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false
